### PR TITLE
fix: inline anonymous "static" node

### PR DESCRIPTION
**Pull request by clason**
Problem: The "trick" of wrapping an anonymous node into a single `choice` or `seq` no longer works as of https://github.com/tree-sitter/tree-sitter/pull/2577

Solution: Inline `"static"` node at its only use site.

@amaanq

### CODE REVIEW

**Comment by clason** [comment]
CI failure looks python-related (workflows need update?) @ObserverOfTime

**Comment by ObserverOfTime** [comment]
The workflows are using Node 16. You can either update them or switch to the official workflows.

**Comment by clason** [comment]
Not sure what the issue is now. If you do, could you just push a commit switching to the official workflows?

**Comment by ObserverOfTime** [comment]
`binding.gyp` is missing the scanner.

**Comment by ObserverOfTime** [comment]
Feel free to remove the lint workflow. :)

**Pull request merged**
